name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Add Helm repos
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Install yamllint
        run: sudo apt-get update && sudo apt-get install -y yamllint

      - name: Lint YAML
        run: yamllint -s .

      - name: Validate Helm rendering with provided values
        run: |
          if [ -f helm/values/monitoring.values.yaml ]; then
            helm template mon prometheus-community/kube-prometheus-stack \
              -f helm/values/monitoring.values.yaml -n monitoring > /dev/null
          else
            echo "No values file found at helm/values/monitoring.values.yaml; skipping template check."
          fi


